// Code generated by protoc-gen-go. DO NOT EDIT.
package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductInfo struct {
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle      string `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	MainImage     string `protobuf:"bytes,5,opt,name=mainImage,proto3" json:"mainImage,omitempty"`
	SubImages     string `protobuf:"bytes,6,opt,name=subImages,proto3" json:"subImages,omitempty"`
	Detail        string `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	Spec          string `protobuf:"bytes,8,opt,name=spec,proto3" json:"spec,omitempty"`
	Price         int64  `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice int64  `protobuf:"varint,10,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Stock         int32  `protobuf:"varint,11,opt,name=stock,proto3" json:"stock,omitempty"`
	Sales         int32  `protobuf:"varint,12,opt,name=sales,proto3" json:"sales,omitempty"`
	Status        int32  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Brand         string `protobuf:"bytes,14,opt,name=brand,proto3" json:"brand,omitempty"`
	CreatedAt     string `protobuf:"bytes,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string `protobuf:"bytes,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *ProductInfo) Reset()         {}
func (x *ProductInfo) String() string { return "" }
func (*ProductInfo) ProtoMessage()    {}
func (x *ProductInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *ProductInfo) GetId() int64            { return x.Id }
func (x *ProductInfo) GetCategoryId() int64    { return x.CategoryId }
func (x *ProductInfo) GetName() string         { return x.Name }
func (x *ProductInfo) GetSubtitle() string     { return x.Subtitle }
func (x *ProductInfo) GetMainImage() string    { return x.MainImage }
func (x *ProductInfo) GetSubImages() string    { return x.SubImages }
func (x *ProductInfo) GetDetail() string       { return x.Detail }
func (x *ProductInfo) GetSpec() string         { return x.Spec }
func (x *ProductInfo) GetPrice() int64         { return x.Price }
func (x *ProductInfo) GetOriginalPrice() int64 { return x.OriginalPrice }
func (x *ProductInfo) GetStock() int32         { return x.Stock }
func (x *ProductInfo) GetSales() int32         { return x.Sales }
func (x *ProductInfo) GetStatus() int32        { return x.Status }
func (x *ProductInfo) GetBrand() string        { return x.Brand }
func (x *ProductInfo) GetCreatedAt() string    { return x.CreatedAt }
func (x *ProductInfo) GetUpdatedAt() string    { return x.UpdatedAt }

type CategoryInfo struct {
	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId  int64  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder int32  `protobuf:"varint,4,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	Status    int32  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CategoryInfo) Reset()         {}
func (x *CategoryInfo) String() string { return "" }
func (*CategoryInfo) ProtoMessage()    {}
func (x *CategoryInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *CategoryInfo) GetId() int64         { return x.Id }
func (x *CategoryInfo) GetParentId() int64   { return x.ParentId }
func (x *CategoryInfo) GetName() string      { return x.Name }
func (x *CategoryInfo) GetSortOrder() int32  { return x.SortOrder }
func (x *CategoryInfo) GetStatus() int32     { return x.Status }

type CreateProductRequest struct {
	CategoryId    int64  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle      string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	MainImage     string `protobuf:"bytes,4,opt,name=mainImage,proto3" json:"mainImage,omitempty"`
	SubImages     string `protobuf:"bytes,5,opt,name=subImages,proto3" json:"subImages,omitempty"`
	Detail        string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Spec          string `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Price         int64  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice int64  `protobuf:"varint,9,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Stock         int32  `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	Brand         string `protobuf:"bytes,11,opt,name=brand,proto3" json:"brand,omitempty"`
}

func (x *CreateProductRequest) Reset()         {}
func (x *CreateProductRequest) String() string { return "" }
func (*CreateProductRequest) ProtoMessage()    {}
func (x *CreateProductRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateProductRequest) GetCategoryId() int64    { return x.CategoryId }
func (x *CreateProductRequest) GetName() string         { return x.Name }
func (x *CreateProductRequest) GetSubtitle() string     { return x.Subtitle }
func (x *CreateProductRequest) GetMainImage() string    { return x.MainImage }
func (x *CreateProductRequest) GetSubImages() string    { return x.SubImages }
func (x *CreateProductRequest) GetDetail() string       { return x.Detail }
func (x *CreateProductRequest) GetSpec() string         { return x.Spec }
func (x *CreateProductRequest) GetPrice() int64         { return x.Price }
func (x *CreateProductRequest) GetOriginalPrice() int64 { return x.OriginalPrice }
func (x *CreateProductRequest) GetStock() int32         { return x.Stock }
func (x *CreateProductRequest) GetBrand() string        { return x.Brand }

type CreateProductResponse struct {
	Product *ProductInfo `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *CreateProductResponse) Reset()         {}
func (x *CreateProductResponse) String() string { return "" }
func (*CreateProductResponse) ProtoMessage()    {}
func (x *CreateProductResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateProductResponse) GetProduct() *ProductInfo { return x.Product }

type GetProductRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProductRequest) Reset()         {}
func (x *GetProductRequest) String() string { return "" }
func (*GetProductRequest) ProtoMessage()    {}
func (x *GetProductRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetProductRequest) GetId() int64 { return x.Id }

type GetProductResponse struct {
	Product *ProductInfo `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *GetProductResponse) Reset()         {}
func (x *GetProductResponse) String() string { return "" }
func (*GetProductResponse) ProtoMessage()    {}
func (x *GetProductResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *GetProductResponse) GetProduct() *ProductInfo { return x.Product }

type UpdateProductRequest struct {
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle      string `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	MainImage     string `protobuf:"bytes,5,opt,name=mainImage,proto3" json:"mainImage,omitempty"`
	SubImages     string `protobuf:"bytes,6,opt,name=subImages,proto3" json:"subImages,omitempty"`
	Detail        string `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	Spec          string `protobuf:"bytes,8,opt,name=spec,proto3" json:"spec,omitempty"`
	Price         int64  `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice int64  `protobuf:"varint,10,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Status        int32  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Brand         string `protobuf:"bytes,12,opt,name=brand,proto3" json:"brand,omitempty"`
}

func (x *UpdateProductRequest) Reset()         {}
func (x *UpdateProductRequest) String() string { return "" }
func (*UpdateProductRequest) ProtoMessage()    {}
func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *UpdateProductRequest) GetId() int64            { return x.Id }
func (x *UpdateProductRequest) GetCategoryId() int64    { return x.CategoryId }
func (x *UpdateProductRequest) GetName() string         { return x.Name }
func (x *UpdateProductRequest) GetSubtitle() string     { return x.Subtitle }
func (x *UpdateProductRequest) GetMainImage() string    { return x.MainImage }
func (x *UpdateProductRequest) GetSubImages() string    { return x.SubImages }
func (x *UpdateProductRequest) GetDetail() string       { return x.Detail }
func (x *UpdateProductRequest) GetSpec() string         { return x.Spec }
func (x *UpdateProductRequest) GetPrice() int64         { return x.Price }
func (x *UpdateProductRequest) GetOriginalPrice() int64 { return x.OriginalPrice }
func (x *UpdateProductRequest) GetStatus() int32        { return x.Status }
func (x *UpdateProductRequest) GetBrand() string        { return x.Brand }

type UpdateProductResponse struct {
	Product *ProductInfo `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *UpdateProductResponse) Reset()         {}
func (x *UpdateProductResponse) String() string { return "" }
func (*UpdateProductResponse) ProtoMessage()    {}
func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *UpdateProductResponse) GetProduct() *ProductInfo { return x.Product }

type ListProductRequest struct {
	Page       int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	CategoryId int64  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Keyword    string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *ListProductRequest) Reset()         {}
func (x *ListProductRequest) String() string { return "" }
func (*ListProductRequest) ProtoMessage()    {}
func (x *ListProductRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ListProductRequest) GetPage() int32       { return x.Page }
func (x *ListProductRequest) GetPageSize() int32   { return x.PageSize }
func (x *ListProductRequest) GetCategoryId() int64 { return x.CategoryId }
func (x *ListProductRequest) GetKeyword() string   { return x.Keyword }

type ListProductResponse struct {
	Products []*ProductInfo `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total    int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListProductResponse) Reset()         {}
func (x *ListProductResponse) String() string { return "" }
func (*ListProductResponse) ProtoMessage()    {}
func (x *ListProductResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ListProductResponse) GetProducts() []*ProductInfo { return x.Products }
func (x *ListProductResponse) GetTotal() int64              { return x.Total }

type GetProductListRequest struct {
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetProductListRequest) Reset()         {}
func (x *GetProductListRequest) String() string { return "" }
func (*GetProductListRequest) ProtoMessage()    {}
func (x *GetProductListRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetProductListRequest) GetIds() []int64 { return x.Ids }

type GetProductListResponse struct {
	Products []*ProductInfo `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *GetProductListResponse) Reset()         {}
func (x *GetProductListResponse) String() string { return "" }
func (*GetProductListResponse) ProtoMessage()    {}
func (x *GetProductListResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *GetProductListResponse) GetProducts() []*ProductInfo { return x.Products }

type ListCategoryRequest struct {
	ParentId int64 `protobuf:"varint,1,opt,name=parentId,proto3" json:"parentId,omitempty"`
}

func (x *ListCategoryRequest) Reset()         {}
func (x *ListCategoryRequest) String() string { return "" }
func (*ListCategoryRequest) ProtoMessage()    {}
func (x *ListCategoryRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ListCategoryRequest) GetParentId() int64 { return x.ParentId }

type ListCategoryResponse struct {
	Categories []*CategoryInfo `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *ListCategoryResponse) Reset()         {}
func (x *ListCategoryResponse) String() string { return "" }
func (*ListCategoryResponse) ProtoMessage()    {}
func (x *ListCategoryResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ListCategoryResponse) GetCategories() []*CategoryInfo { return x.Categories }

var File_product_proto protoreflect.FileDescriptor
