// Code generated by protoc-gen-go. DO NOT EDIT.
package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type StockInfo struct {
	Id        int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId int64 `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Total     int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Available int32 `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	LockStock int32 `protobuf:"varint,5,opt,name=lockStock,proto3" json:"lockStock,omitempty"`
	Sales     int32 `protobuf:"varint,6,opt,name=sales,proto3" json:"sales,omitempty"`
}
func (x *StockInfo) Reset() {}
func (x *StockInfo) String() string { return "" }
func (*StockInfo) ProtoMessage() {}
func (x *StockInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *StockInfo) GetId() int64 { return x.Id }
func (x *StockInfo) GetProductId() int64 { return x.ProductId }
func (x *StockInfo) GetTotal() int32 { return x.Total }
func (x *StockInfo) GetAvailable() int32 { return x.Available }
func (x *StockInfo) GetLockStock() int32 { return x.LockStock }
func (x *StockInfo) GetSales() int32 { return x.Sales }

type CreateStockRequest struct {
	ProductId int64 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Num     int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}
func (x *CreateStockRequest) Reset() {}
func (x *CreateStockRequest) String() string { return "" }
func (*CreateStockRequest) ProtoMessage() {}
func (x *CreateStockRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateStockRequest) GetProductId() int64 { return x.ProductId }
func (x *CreateStockRequest) GetNum() int32 { return x.Num }

type CreateStockResponse struct {
	Stock *StockInfo `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
}
func (x *CreateStockResponse) Reset() {}
func (x *CreateStockResponse) String() string { return "" }
func (*CreateStockResponse) ProtoMessage() {}
func (x *CreateStockResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateStockResponse) GetStock() *StockInfo { return x.Stock }

type GetStockRequest struct {
	ProductId int64 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
}
func (x *GetStockRequest) Reset() {}
func (x *GetStockRequest) String() string { return "" }
func (*GetStockRequest) ProtoMessage() {}
func (x *GetStockRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetStockRequest) GetProductId() int64 { return x.ProductId }

type GetStockResponse struct {
	Stock *StockInfo `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
}
func (x *GetStockResponse) Reset() {}
func (x *GetStockResponse) String() string { return "" }
func (*GetStockResponse) ProtoMessage() {}
func (x *GetStockResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *GetStockResponse) GetStock() *StockInfo { return x.Stock }

type DeductStockRequest struct {
	ProductId int64  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Num       int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	OrderNo   string `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
}
func (x *DeductStockRequest) Reset() {}
func (x *DeductStockRequest) String() string { return "" }
func (*DeductStockRequest) ProtoMessage() {}
func (x *DeductStockRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DeductStockRequest) GetProductId() int64 { return x.ProductId }
func (x *DeductStockRequest) GetNum() int32 { return x.Num }
func (x *DeductStockRequest) GetOrderNo() string { return x.OrderNo }

type DeductStockResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}
func (x *DeductStockResponse) Reset() {}
func (x *DeductStockResponse) String() string { return "" }
func (*DeductStockResponse) ProtoMessage() {}
func (x *DeductStockResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *DeductStockResponse) GetSuccess() bool { return x.Success }

type ReturnStockRequest struct {
	ProductId int64  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Num       int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	OrderNo   string `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
}
func (x *ReturnStockRequest) Reset() {}
func (x *ReturnStockRequest) String() string { return "" }
func (*ReturnStockRequest) ProtoMessage() {}
func (x *ReturnStockRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ReturnStockRequest) GetProductId() int64 { return x.ProductId }
func (x *ReturnStockRequest) GetNum() int32 { return x.Num }
func (x *ReturnStockRequest) GetOrderNo() string { return x.OrderNo }

type ReturnStockResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}
func (x *ReturnStockResponse) Reset() {}
func (x *ReturnStockResponse) String() string { return "" }
func (*ReturnStockResponse) ProtoMessage() {}
func (x *ReturnStockResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ReturnStockResponse) GetSuccess() bool { return x.Success }

type ConfirmStockRequest struct {
	ProductId int64  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Num       int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	OrderNo   string `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
}
func (x *ConfirmStockRequest) Reset() {}
func (x *ConfirmStockRequest) String() string { return "" }
func (*ConfirmStockRequest) ProtoMessage() {}
func (x *ConfirmStockRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ConfirmStockRequest) GetProductId() int64 { return x.ProductId }
func (x *ConfirmStockRequest) GetNum() int32 { return x.Num }
func (x *ConfirmStockRequest) GetOrderNo() string { return x.OrderNo }

type ConfirmStockResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}
func (x *ConfirmStockResponse) Reset() {}
func (x *ConfirmStockResponse) String() string { return "" }
func (*ConfirmStockResponse) ProtoMessage() {}
func (x *ConfirmStockResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ConfirmStockResponse) GetSuccess() bool { return x.Success }

var File_stock_proto protoreflect.FileDescriptor
