// Code generated by protoc-gen-go. DO NOT EDIT.
package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type OrderItemInfo struct {
	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId    int64  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	ProductName  string `protobuf:"bytes,3,opt,name=productName,proto3" json:"productName,omitempty"`
	ProductImage string `protobuf:"bytes,4,opt,name=productImage,proto3" json:"productImage,omitempty"`
	Price        int64  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Num          int32  `protobuf:"varint,6,opt,name=num,proto3" json:"num,omitempty"`
	TotalPrice   int64  `protobuf:"varint,7,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
}
func (x *OrderItemInfo) Reset() {}
func (x *OrderItemInfo) String() string { return "" }
func (*OrderItemInfo) ProtoMessage() {}
func (x *OrderItemInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *OrderItemInfo) GetId() int64 { return x.Id }
func (x *OrderItemInfo) GetProductId() int64 { return x.ProductId }
func (x *OrderItemInfo) GetProductName() string { return x.ProductName }
func (x *OrderItemInfo) GetProductImage() string { return x.ProductImage }
func (x *OrderItemInfo) GetPrice() int64 { return x.Price }
func (x *OrderItemInfo) GetNum() int32 { return x.Num }
func (x *OrderItemInfo) GetTotalPrice() int64 { return x.TotalPrice }

type OrderInfo struct {
	Id              int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo         string           `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId          int64            `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TotalAmount     int64            `protobuf:"varint,4,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	PayAmount       int64            `protobuf:"varint,5,opt,name=payAmount,proto3" json:"payAmount,omitempty"`
	FreightAmount   int64            `protobuf:"varint,6,opt,name=freightAmount,proto3" json:"freightAmount,omitempty"`
	DiscountAmount  int64            `protobuf:"varint,7,opt,name=discountAmount,proto3" json:"discountAmount,omitempty"`
	Status          int32            `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	PayType         int32            `protobuf:"varint,9,opt,name=payType,proto3" json:"payType,omitempty"`
	ReceiverName    string           `protobuf:"bytes,10,opt,name=receiverName,proto3" json:"receiverName,omitempty"`
	ReceiverPhone   string           `protobuf:"bytes,11,opt,name=receiverPhone,proto3" json:"receiverPhone,omitempty"`
	ReceiverAddress string           `protobuf:"bytes,12,opt,name=receiverAddress,proto3" json:"receiverAddress,omitempty"`
	Remark          string           `protobuf:"bytes,13,opt,name=remark,proto3" json:"remark,omitempty"`
	Items           []*OrderItemInfo `protobuf:"bytes,14,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt       string           `protobuf:"bytes,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       string           `protobuf:"bytes,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}
func (x *OrderInfo) Reset() {}
func (x *OrderInfo) String() string { return "" }
func (*OrderInfo) ProtoMessage() {}
func (x *OrderInfo) ProtoReflect() protoreflect.Message { return nil }
func (x *OrderInfo) GetId() int64 { return x.Id }
func (x *OrderInfo) GetOrderNo() string { return x.OrderNo }
func (x *OrderInfo) GetUserId() int64 { return x.UserId }
func (x *OrderInfo) GetTotalAmount() int64 { return x.TotalAmount }
func (x *OrderInfo) GetPayAmount() int64 { return x.PayAmount }
func (x *OrderInfo) GetFreightAmount() int64 { return x.FreightAmount }
func (x *OrderInfo) GetDiscountAmount() int64 { return x.DiscountAmount }
func (x *OrderInfo) GetStatus() int32 { return x.Status }
func (x *OrderInfo) GetPayType() int32 { return x.PayType }
func (x *OrderInfo) GetReceiverName() string { return x.ReceiverName }
func (x *OrderInfo) GetReceiverPhone() string { return x.ReceiverPhone }
func (x *OrderInfo) GetReceiverAddress() string { return x.ReceiverAddress }
func (x *OrderInfo) GetRemark() string { return x.Remark }
func (x *OrderInfo) GetItems() []*OrderItemInfo { return x.Items }
func (x *OrderInfo) GetCreatedAt() string { return x.CreatedAt }
func (x *OrderInfo) GetUpdatedAt() string { return x.UpdatedAt }

type OrderItemReq struct {
	ProductId int64 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Num       int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Price     int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}
func (x *OrderItemReq) Reset() {}
func (x *OrderItemReq) String() string { return "" }
func (*OrderItemReq) ProtoMessage() {}
func (x *OrderItemReq) ProtoReflect() protoreflect.Message { return nil }
func (x *OrderItemReq) GetProductId() int64 { return x.ProductId }
func (x *OrderItemReq) GetNum() int32 { return x.Num }
func (x *OrderItemReq) GetPrice() int64 { return x.Price }

type CreateOrderRequest struct {
	UserId          int64           `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Items           []*OrderItemReq `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ReceiverName    string          `protobuf:"bytes,3,opt,name=receiverName,proto3" json:"receiverName,omitempty"`
	ReceiverPhone   string          `protobuf:"bytes,4,opt,name=receiverPhone,proto3" json:"receiverPhone,omitempty"`
	ReceiverAddress string          `protobuf:"bytes,5,opt,name=receiverAddress,proto3" json:"receiverAddress,omitempty"`
	Remark          string          `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
}
func (x *CreateOrderRequest) Reset() {}
func (x *CreateOrderRequest) String() string { return "" }
func (*CreateOrderRequest) ProtoMessage() {}
func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateOrderRequest) GetUserId() int64 { return x.UserId }
func (x *CreateOrderRequest) GetItems() []*OrderItemReq { return x.Items }
func (x *CreateOrderRequest) GetReceiverName() string { return x.ReceiverName }
func (x *CreateOrderRequest) GetReceiverPhone() string { return x.ReceiverPhone }
func (x *CreateOrderRequest) GetReceiverAddress() string { return x.ReceiverAddress }
func (x *CreateOrderRequest) GetRemark() string { return x.Remark }

type CreateOrderResponse struct {
	OrderNo   string `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Id        int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PayAmount int64  `protobuf:"varint,3,opt,name=payAmount,proto3" json:"payAmount,omitempty"`
}
func (x *CreateOrderResponse) Reset() {}
func (x *CreateOrderResponse) String() string { return "" }
func (*CreateOrderResponse) ProtoMessage() {}
func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateOrderResponse) GetOrderNo() string { return x.OrderNo }
func (x *CreateOrderResponse) GetId() int64 { return x.Id }
func (x *CreateOrderResponse) GetPayAmount() int64 { return x.PayAmount }

type GetOrderRequest struct {
	OrderNo string `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
}
func (x *GetOrderRequest) Reset() {}
func (x *GetOrderRequest) String() string { return "" }
func (*GetOrderRequest) ProtoMessage() {}
func (x *GetOrderRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetOrderRequest) GetOrderNo() string { return x.OrderNo }

type GetOrderResponse struct {
	Order *OrderInfo `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}
func (x *GetOrderResponse) Reset() {}
func (x *GetOrderResponse) String() string { return "" }
func (*GetOrderResponse) ProtoMessage() {}
func (x *GetOrderResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *GetOrderResponse) GetOrder() *OrderInfo { return x.Order }

type ListOrderRequest struct {
	UserId   int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}
func (x *ListOrderRequest) Reset() {}
func (x *ListOrderRequest) String() string { return "" }
func (*ListOrderRequest) ProtoMessage() {}
func (x *ListOrderRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ListOrderRequest) GetUserId() int64 { return x.UserId }
func (x *ListOrderRequest) GetPage() int32 { return x.Page }
func (x *ListOrderRequest) GetPageSize() int32 { return x.PageSize }

type ListOrderResponse struct {
	Orders []*OrderInfo `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total  int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}
func (x *ListOrderResponse) Reset() {}
func (x *ListOrderResponse) String() string { return "" }
func (*ListOrderResponse) ProtoMessage() {}
func (x *ListOrderResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ListOrderResponse) GetOrders() []*OrderInfo { return x.Orders }
func (x *ListOrderResponse) GetTotal() int64 { return x.Total }

type CancelOrderRequest struct {
	OrderNo string `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}
func (x *CancelOrderRequest) Reset() {}
func (x *CancelOrderRequest) String() string { return "" }
func (*CancelOrderRequest) ProtoMessage() {}
func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CancelOrderRequest) GetOrderNo() string { return x.OrderNo }
func (x *CancelOrderRequest) GetUserId() int64 { return x.UserId }

type CancelOrderResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}
func (x *CancelOrderResponse) Reset() {}
func (x *CancelOrderResponse) String() string { return "" }
func (*CancelOrderResponse) ProtoMessage() {}
func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CancelOrderResponse) GetSuccess() bool { return x.Success }

type PayOrderRequest struct {
	OrderNo string `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	PayType int32  `protobuf:"varint,3,opt,name=payType,proto3" json:"payType,omitempty"`
}
func (x *PayOrderRequest) Reset() {}
func (x *PayOrderRequest) String() string { return "" }
func (*PayOrderRequest) ProtoMessage() {}
func (x *PayOrderRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *PayOrderRequest) GetOrderNo() string { return x.OrderNo }
func (x *PayOrderRequest) GetUserId() int64 { return x.UserId }
func (x *PayOrderRequest) GetPayType() int32 { return x.PayType }

type PayOrderResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}
func (x *PayOrderResponse) Reset() {}
func (x *PayOrderResponse) String() string { return "" }
func (*PayOrderResponse) ProtoMessage() {}
func (x *PayOrderResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *PayOrderResponse) GetSuccess() bool { return x.Success }

var File_order_proto protoreflect.FileDescriptor
